### ISSUE TITLE
Lock icon missing in options legend and on build time options 

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/antora-ui-quarkiverse#55]
There is some CSS for the $subj that apparently does not work. It perhaps has to do with #34.

Expected: 
Like on https://quarkus.io/guides/all-config
![image](https://github.com/quarkiverse/antora-ui-quarkiverse/assets/1826249/c5f932fd-e454-472f-86fa-71eda9660bfb)

Actual:
https://docs.quarkiverse.io/quarkus-cxf/dev/reference/extensions/quarkus-cxf.html
![image](https://github.com/quarkiverse/antora-ui-quarkiverse/assets/1826249/e2e64f41-a287-4ca2-87ef-ca70647e2132)

**Comment by holly-cummins** [comment]
Will investigate.
