### ISSUE TITLE
Training link http://quarkus.io/training retruns 404

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/antora-ui-quarkiverse#86]
Playing with some code for link verification on [generated Antora sites](https://github.com/quarkiverse/quarkus-antora/issues/23), the first hit was the Training link in Quarkus Antora UI

https://github.com/quarkiverse/antora-ui-quarkiverse/blob/01216589bb1e2bc3985c79cb23b191945fd27e0b/src/partials/header-content.hbs#L24

**Comment by holly-cummins** [comment]
Automated dead link checking FTW. Thanks, @ppalaga!
